In [1]:
import numpy as np

a = np.array([[3,4,5],[2,3,4]])
b = np.array([[1,3],[2,4],[3,5]])

np.dot(a,b)

array([[26, 50],
       [20, 38]])

In [2]:
np.where(a>3, 1, 0)

array([[0, 1, 1],
       [0, 0, 1]])

In [ ]:
def activations(inputs):
    # compute activations
    activations = np.dot(inputs, self.weights)

    # Threshold the activations
    return np.where(activations > 0, 1,0)

In [3]:
np.transpose(a)

array([[3, 2],
       [4, 3],
       [5, 4]])

In [ ]:
self.weights -= eta*np.dot(np.transpose(inputs), self.activations-targets)

inputs = np.concatenate((inputs, -np.ones((self.nData,1))), axis=1)

weights = np.random.rand(nIn+1,nOut)*0.1-0.05